# Podfile
platform :ios, '13.0'

target 'FKLogger' do
  use_frameworks! :linkage => :static
  pod 'CocoaLumberjack/Swift', '~> 3.8'
  pod 'SSZipArchive'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end